[versions]
agp = "8.5.2"
kotlin = "2.0.0"
coreKtx = "1.13.1"
compose = "1.7.1"
compose-material3 = "1.3.0"
cmp-plugin = "1.7.0-beta01"
decompose = "3.2.0-beta01"
essenty = "2.2.0-beta01"
androidx-activityCompose = "1.9.2"
lifecycleRuntimeKtx = "2.8.5"
cupertino = "0.1.0-alpha04"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }

decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extension-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
decompose-extension-compose-experimental = { module = "com.arkivanov.decompose:extensions-compose-experimental", version.ref = "decompose" }
decompose-extension-android = { module = "com.arkivanov.decompose:extensions-android", version.ref = "decompose" }
decompose-essenty = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }

cupertino-navigation = { module = "io.github.alexzhirkevich:cupertino-decompose", version.ref = "cupertino"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "cmp-plugin" }
